"""initial schema

Revision ID: 8db02c2cd0af
Revises: 
Create Date: 2026-07-18 21:12:58.030800

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8db02c2cd0af'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hotel',
    sa.Column('hotel_id', sa.UUID(), nullable=False),
    sa.Column('slug', sa.String(length=64), nullable=False),
    sa.Column('legal_name', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('city', sa.String(length=128), nullable=False),
    sa.Column('country', sa.String(length=2), nullable=False),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lon', sa.Float(), nullable=True),
    sa.Column('star_rating', sa.SmallInteger(), nullable=True),
    sa.Column('status', sa.Enum('onboarding', 'active', 'suspended', name='hotel_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('hotel_id')
    )
    op.create_index(op.f('ix_hotel_slug'), 'hotel', ['slug'], unique=True)
    op.create_table('traveler_account',
    sa.Column('traveler_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('traveler_id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('hotel_credential',
    sa.Column('hotel_id', sa.UUID(), nullable=False),
    sa.Column('api_base_url', sa.String(length=512), nullable=False),
    sa.Column('api_key_encrypted', sa.String(length=1024), nullable=False),
    sa.Column('oauth_client_id', sa.String(length=255), nullable=True),
    sa.Column('webhook_secret_encrypted', sa.String(length=1024), nullable=False),
    sa.Column('hold_ttl_seconds_default', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['hotel_id'], ['hotel.hotel_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('hotel_id')
    )
    op.create_table('room_type_index',
    sa.Column('global_room_type_id', sa.String(length=255), nullable=False),
    sa.Column('hotel_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('max_occupancy_adults', sa.Integer(), nullable=False),
    sa.Column('max_occupancy_children', sa.Integer(), nullable=False),
    sa.Column('amenities', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('photos', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['hotel_id'], ['hotel.hotel_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('global_room_type_id')
    )
    op.create_index(op.f('ix_room_type_index_hotel_id'), 'room_type_index', ['hotel_id'], unique=False)
    op.create_table('sync_health',
    sa.Column('hotel_id', sa.UUID(), nullable=False),
    sa.Column('last_event_received_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_reconciliation_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('consecutive_failures', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('healthy', 'degraded', 'down', name='sync_health_status'), nullable=False),
    sa.ForeignKeyConstraint(['hotel_id'], ['hotel.hotel_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('hotel_id')
    )
    op.create_table('webhook_inbox',
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('hotel_id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['hotel_id'], ['hotel.hotel_id'], ),
    sa.PrimaryKeyConstraint('event_id')
    )
    op.create_index(op.f('ix_webhook_inbox_hotel_id'), 'webhook_inbox', ['hotel_id'], unique=False)
    op.create_table('booking_reference',
    sa.Column('agg_booking_id', sa.UUID(), nullable=False),
    sa.Column('traveler_id', sa.UUID(), nullable=False),
    sa.Column('hotel_id', sa.UUID(), nullable=False),
    sa.Column('hotel_hold_id', sa.String(length=255), nullable=False),
    sa.Column('hotel_reservation_id', sa.String(length=255), nullable=True),
    sa.Column('global_room_type_id', sa.String(length=255), nullable=False),
    sa.Column('check_in', sa.Date(), nullable=False),
    sa.Column('check_out', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('pending_payment', 'held', 'confirmed', 'cancelled', 'expired', name='booking_reference_status'), nullable=False),
    sa.Column('payment_id', sa.UUID(), nullable=True),
    sa.Column('hold_expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['global_room_type_id'], ['room_type_index.global_room_type_id'], ),
    sa.ForeignKeyConstraint(['hotel_id'], ['hotel.hotel_id'], ),
    sa.ForeignKeyConstraint(['payment_id'], ['payment_transaction.payment_id'], name='fk_booking_reference_payment_id', use_alter=True),
    sa.ForeignKeyConstraint(['traveler_id'], ['traveler_account.traveler_id'], ),
    sa.PrimaryKeyConstraint('agg_booking_id'),
    sa.UniqueConstraint('hotel_id', 'hotel_hold_id', name='uq_booking_reference_hotel_hold')
    )
    op.create_index(op.f('ix_booking_reference_global_room_type_id'), 'booking_reference', ['global_room_type_id'], unique=False)
    op.create_index(op.f('ix_booking_reference_hotel_id'), 'booking_reference', ['hotel_id'], unique=False)
    op.create_index(op.f('ix_booking_reference_traveler_id'), 'booking_reference', ['traveler_id'], unique=False)
    op.create_table('rate_availability_index',
    sa.Column('global_room_type_id', sa.String(length=255), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('rate_plan_code', sa.String(length=32), nullable=False),
    sa.Column('price_minor', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('rooms_available_cached', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source', sa.Enum('webhook', 'reconciliation', name='sync_source'), nullable=False),
    sa.ForeignKeyConstraint(['global_room_type_id'], ['room_type_index.global_room_type_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('global_room_type_id', 'date', 'rate_plan_code')
    )
    op.create_table('payment_transaction',
    sa.Column('payment_id', sa.UUID(), nullable=False),
    sa.Column('agg_booking_id', sa.UUID(), nullable=False),
    sa.Column('amount_minor', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('gateway_ref', sa.String(length=255), nullable=False),
    sa.Column('status', sa.Enum('pending', 'succeeded', 'failed', 'refunded', name='payment_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['agg_booking_id'], ['booking_reference.agg_booking_id'], ),
    sa.PrimaryKeyConstraint('payment_id')
    )
    op.create_index(op.f('ix_payment_transaction_agg_booking_id'), 'payment_transaction', ['agg_booking_id'], unique=False)
    op.create_table('review',
    sa.Column('review_id', sa.UUID(), nullable=False),
    sa.Column('agg_booking_id', sa.UUID(), nullable=False),
    sa.Column('hotel_id', sa.UUID(), nullable=False),
    sa.Column('rating', sa.SmallInteger(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['agg_booking_id'], ['booking_reference.agg_booking_id'], ),
    sa.ForeignKeyConstraint(['hotel_id'], ['hotel.hotel_id'], ),
    sa.PrimaryKeyConstraint('review_id'),
    sa.UniqueConstraint('agg_booking_id', name='uq_review_one_per_booking')
    )
    op.create_index(op.f('ix_review_agg_booking_id'), 'review', ['agg_booking_id'], unique=False)
    op.create_index(op.f('ix_review_hotel_id'), 'review', ['hotel_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_review_hotel_id'), table_name='review')
    op.drop_index(op.f('ix_review_agg_booking_id'), table_name='review')
    op.drop_table('review')
    op.drop_index(op.f('ix_payment_transaction_agg_booking_id'), table_name='payment_transaction')
    op.drop_table('payment_transaction')
    op.drop_table('rate_availability_index')
    op.drop_index(op.f('ix_booking_reference_traveler_id'), table_name='booking_reference')
    op.drop_index(op.f('ix_booking_reference_hotel_id'), table_name='booking_reference')
    op.drop_index(op.f('ix_booking_reference_global_room_type_id'), table_name='booking_reference')
    op.drop_table('booking_reference')
    op.drop_index(op.f('ix_webhook_inbox_hotel_id'), table_name='webhook_inbox')
    op.drop_table('webhook_inbox')
    op.drop_table('sync_health')
    op.drop_index(op.f('ix_room_type_index_hotel_id'), table_name='room_type_index')
    op.drop_table('room_type_index')
    op.drop_table('hotel_credential')
    op.drop_table('traveler_account')
    op.drop_index(op.f('ix_hotel_slug'), table_name='hotel')
    op.drop_table('hotel')
    # ### end Alembic commands ###
